// Compiles TestUsd.sol into test-usd.ts, which the x402 settlement tests deploy on Anvil. Run it after changing the
// contract: `node packages/x402/test/token/compile.mjs && pnpm format`. It runs solc-js (MIT) through npx, so the
// compiler is not a dependency of the repository.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const SOLC = 'solc@0.8.28';
const here = new URL('.', import.meta.url).pathname;
const out = mkdtempSync(join(tmpdir(), 'test-usd-'));
try {
  execFileSync(
    'npx',
    ['-y', SOLC, '--bin', '--abi', '--optimize', '--base-path', here, '-o', out, 'TestUsd.sol'],
    {
      cwd: here,
      stdio: 'inherit',
    },
  );
  const abi = readFileSync(join(out, 'TestUsd_sol_TestUsd.abi'), 'utf8');
  const bin = readFileSync(join(out, 'TestUsd_sol_TestUsd.bin'), 'utf8').trim();
  writeFileSync(
    join(here, 'test-usd.ts'),
    `// Generated by compile.mjs from TestUsd.sol with ${SOLC} (--optimize); do not edit.
export const testUsdAbi = ${abi} as const;

export const testUsdBytecode = '0x${bin}' as const;
`,
  );
} finally {
  rmSync(out, { recursive: true, force: true });
}
