// Compiles TestEntryPoint.sol into test-entry-point.ts, which the user operation tests put on Anvil. Run it after
// changing the contracts: `node packages/viem/test/entry-point/compile.mjs && pnpm format`. It runs solc-js (MIT)
// through npx, so the compiler is not a dependency of the repository.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const SOLC = 'solc@0.8.28';
const CONTRACTS = ['TestEntryPoint', 'TestAccount', 'Reverter'];
const here = new URL('.', import.meta.url).pathname;
const input = {
  language: 'Solidity',
  sources: { 'TestEntryPoint.sol': { content: readFileSync(`${here}TestEntryPoint.sol`, 'utf8') } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { '*': { '*': ['abi', 'evm.deployedBytecode.object'] } },
  },
};
const stdout = execFileSync('npx', ['-y', SOLC, '--standard-json'], {
  cwd: here,
  input: JSON.stringify(input),
  maxBuffer: 64 * 1024 * 1024,
}).toString();
// solc-js prints notices such as ">>> Cannot retry compilation with SMT" before the JSON.
const output = JSON.parse(stdout.slice(stdout.indexOf('{')));
const errors = (output.errors ?? []).filter((e) => e.severity === 'error');
if (errors.length > 0) throw new Error(errors.map((e) => e.formattedMessage).join('\n'));
const exports = CONTRACTS.map((name) => {
  const contract = output.contracts['TestEntryPoint.sol'][name];
  const id = name[0].toLowerCase() + name.slice(1);
  return `export const ${id}Abi = ${JSON.stringify(contract.abi)} as const;\n\nexport const ${id}Code = '0x${contract.evm.deployedBytecode.object}' as const;\n`;
});
writeFileSync(
  `${here}test-entry-point.ts`,
  `// Generated by compile.mjs from TestEntryPoint.sol with ${SOLC} (optimizer on); do not edit.\n// Runtime bytecode: the contracts have no constructor or immutables, so the tests set it with anvil_setCode.\n${exports.join('\n')}`,
);
