// Copies the runtime code of Permit2 and the x402 Permit2 proxies from Base Sepolia into contracts.ts, which the
// Permit2 settlement test installs on Anvil at the same addresses. Tests never run it and never leave localhost; run it
// by hand to refresh the copies: `node packages/x402/test/permit2/fetch.mjs && pnpm format`.
// Permit2 (https://github.com/Uniswap/permit2) and the proxies (https://github.com/coinbase/x402, contracts/evm/src)
// are MIT-licensed.
import { writeFileSync } from 'node:fs';
import { createPublicClient, http } from 'viem';
import { baseSepolia } from 'viem/chains';

const RPC_URL = 'https://sepolia.base.org';
const CONTRACTS = {
  PERMIT2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  EXACT_PROXY: '0x402085c248EeA27D92E8b30b2C58ed07f9E20001',
  UPTO_PROXY: '0x4020A4f3b7b90ccA423B9fabCc0CE57C6C240002',
};

const client = createPublicClient({ chain: baseSepolia, transport: http(RPC_URL) });
const blockNumber = await client.getBlockNumber();
let body = '';
for (const [name, address] of Object.entries(CONTRACTS)) {
  const code = await client.getCode({ address, blockNumber });
  if (!code || code === '0x') throw new Error(`no code at ${address} in block ${blockNumber}`);
  body += `\nexport const ${name}_ADDRESS = '${address}' as const;\nexport const ${name}_CODE = '${code}' as const;\n`;
}
writeFileSync(
  new URL('contracts.ts', import.meta.url),
  `// Generated by fetch.mjs; do not edit. Runtime code copied with eth_getCode from Base Sepolia (chain id 84532) at
// block ${blockNumber}, for the Permit2 settlement test to install on Anvil with anvil_setCode at the same addresses.
// Permit2: https://github.com/Uniswap/permit2, MIT. x402ExactPermit2Proxy and x402UptoPermit2Proxy:
// https://github.com/coinbase/x402 (contracts/evm/src), MIT.
${body}`,
);
